image: $GITLAB_REGISTRY/sc-rep/scoding/internal7/docker-images/app_docker_amd64:latest

stages:
  - validate
  - deploy

docker_image_deploy:
  stage: deploy
  services:
    - docker:dind
  only:
    - master
  when: manual
  script:
    - export APP_ENV="prod"
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker login $GITLAB_REGISTRY -u $GITLAB_REGISTRY_USER -p $GITLAB_REGISTRY_PASSWORD
    - php docker.php

docker_image_validate:
  stage: validate
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  script:
    - export APP_ENV="test"
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker login $GITLAB_REGISTRY -u $GITLAB_REGISTRY_USER -p $GITLAB_REGISTRY_PASSWORD
    - php docker.php