version: '3.9'

services:
  image_php:
    image: registry.gitlab.scoding.com/scoding-internal/docker-images/app_php:7.4
    container_name: image_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - "9005:9000"
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
