version: '3.9'

services:
  images_php:
    container_name: images_php
    build: docker/php
    restart: unless-stopped
    tty: true
    depends_on:
      - images_mysql
      - images_nginx
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=symfony-local"
    ports:
      - "9005:9000"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:delegated
    extra_hosts:
      - "docker.for.mac.localhost:host-gateway"
    networks:
      - app-network

  images_mysql:
    build: docker/mysql
    container_name: images_mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: root
    restart: on-failure
    volumes:
      - ./docker/mysql/data:/bitnami/mariadb
    networks:
      - app-network

  images_nginx:
    build: docker/nginx
    container_name: images_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:delegated
      - ./docker/log/nginx:/var/log/nginx
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
