cluster.name: "docker-cluster"
network.host: _eth0_
cluster.initial_master_nodes: "es01,es02,es03"
discovery.seed_hosts: "es01,es02,es03"
bootstrap.memory_lock: true
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.http.ssl.verification_mode: certificate
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.license.self_generated.type: basic
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
