---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: ${KIBANA_SERVERNAME}
server.host: "0.0.0.0"
elasticsearch.hosts: [ ${ELASTICSEARCH_HOST} ]
xpack.monitoring.ui.container.elasticsearch.enabled: false

## X-Pack security credentials
#
elasticsearch.username: ${ELASTICSEARCH_USER}
elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
